// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: calculate/calculator.proto

package calculate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             float64                `protobuf:"fixed64,1,opt,name=a,proto3" json:"a,omitempty"`
	B             float64                `protobuf:"fixed64,2,opt,name=b,proto3" json:"b,omitempty"`
	C             *float64               `protobuf:"fixed64,3,opt,name=c,proto3,oneof" json:"c,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	mi := &file_calculate_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculate_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_calculate_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateRequest) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *CalculateRequest) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *CalculateRequest) GetC() float64 {
	if x != nil && x.C != nil {
		return *x.C
	}
	return 0
}

func (x *CalculateRequest) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type Student struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_calculate_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_calculate_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_calculate_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *Student) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Student) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_calculate_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_calculate_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_calculate_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type CalculateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateResponse) Reset() {
	*x = CalculateResponse{}
	mi := &file_calculate_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse) ProtoMessage() {}

func (x *CalculateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculate_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse.ProtoReflect.Descriptor instead.
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return file_calculate_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_calculate_calculator_proto protoreflect.FileDescriptor

const file_calculate_calculator_proto_rawDesc = "" +
	"\n" +
	"\x1acalculate/calculator.proto\x12\tcalculate\x1a\x19google/protobuf/any.proto\"q\n" +
	"\x10CalculateRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x01R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x01R\x01b\x12\x11\n" +
	"\x01c\x18\x03 \x01(\x01H\x00R\x01c\x88\x01\x01\x12(\n" +
	"\x04data\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x04dataB\x04\n" +
	"\x02_c\"/\n" +
	"\aStudent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\"4\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\"+\n" +
	"\x11CalculateResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result2N\n" +
	"\n" +
	"Calculator\x12@\n" +
	"\x03Add\x12\x1b.calculate.CalculateRequest\x1a\x1c.calculate.CalculateResponseB\x16Z\x14demo/proto/calculateb\x06proto3"

var (
	file_calculate_calculator_proto_rawDescOnce sync.Once
	file_calculate_calculator_proto_rawDescData []byte
)

func file_calculate_calculator_proto_rawDescGZIP() []byte {
	file_calculate_calculator_proto_rawDescOnce.Do(func() {
		file_calculate_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculate_calculator_proto_rawDesc), len(file_calculate_calculator_proto_rawDesc)))
	})
	return file_calculate_calculator_proto_rawDescData
}

var file_calculate_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_calculate_calculator_proto_goTypes = []any{
	(*CalculateRequest)(nil),  // 0: calculate.CalculateRequest
	(*Student)(nil),           // 1: calculate.Student
	(*User)(nil),              // 2: calculate.User
	(*CalculateResponse)(nil), // 3: calculate.CalculateResponse
	(*anypb.Any)(nil),         // 4: google.protobuf.Any
}
var file_calculate_calculator_proto_depIdxs = []int32{
	4, // 0: calculate.CalculateRequest.data:type_name -> google.protobuf.Any
	0, // 1: calculate.Calculator.Add:input_type -> calculate.CalculateRequest
	3, // 2: calculate.Calculator.Add:output_type -> calculate.CalculateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_calculate_calculator_proto_init() }
func file_calculate_calculator_proto_init() {
	if File_calculate_calculator_proto != nil {
		return
	}
	file_calculate_calculator_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculate_calculator_proto_rawDesc), len(file_calculate_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculate_calculator_proto_goTypes,
		DependencyIndexes: file_calculate_calculator_proto_depIdxs,
		MessageInfos:      file_calculate_calculator_proto_msgTypes,
	}.Build()
	File_calculate_calculator_proto = out.File
	file_calculate_calculator_proto_goTypes = nil
	file_calculate_calculator_proto_depIdxs = nil
}
