// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: notice_proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoticeReaderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Msg   string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	// Types that are valid to be assigned to NoticeWay:
	//
	//	*NoticeReaderRequest_Email
	//	*NoticeReaderRequest_Phone
	NoticeWay     isNoticeReaderRequest_NoticeWay `protobuf_oneof:"notice_way"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeReaderRequest) Reset() {
	*x = NoticeReaderRequest{}
	mi := &file_notice_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeReaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeReaderRequest) ProtoMessage() {}

func (x *NoticeReaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notice_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeReaderRequest.ProtoReflect.Descriptor instead.
func (*NoticeReaderRequest) Descriptor() ([]byte, []int) {
	return file_notice_proto_proto_rawDescGZIP(), []int{0}
}

func (x *NoticeReaderRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *NoticeReaderRequest) GetNoticeWay() isNoticeReaderRequest_NoticeWay {
	if x != nil {
		return x.NoticeWay
	}
	return nil
}

func (x *NoticeReaderRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.NoticeWay.(*NoticeReaderRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *NoticeReaderRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.NoticeWay.(*NoticeReaderRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

type isNoticeReaderRequest_NoticeWay interface {
	isNoticeReaderRequest_NoticeWay()
}

type NoticeReaderRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

type NoticeReaderRequest_Phone struct {
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3,oneof"`
}

func (*NoticeReaderRequest_Email) isNoticeReaderRequest_NoticeWay() {}

func (*NoticeReaderRequest_Phone) isNoticeReaderRequest_NoticeWay() {}

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Price1        *int64                 `protobuf:"varint,2,opt,name=price1,proto3,oneof" json:"price1,omitempty"`
	Price2        *wrapperspb.Int64Value `protobuf:"bytes,3,opt,name=price2,proto3" json:"price2,omitempty"`
	Price3        int64                  `protobuf:"varint,4,opt,name=price3,proto3" json:"price3,omitempty"`
	Info          *Book_Info             `protobuf:"bytes,6,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_notice_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_notice_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_notice_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetPrice1() int64 {
	if x != nil && x.Price1 != nil {
		return *x.Price1
	}
	return 0
}

func (x *Book) GetPrice2() *wrapperspb.Int64Value {
	if x != nil {
		return x.Price2
	}
	return nil
}

func (x *Book) GetPrice3() int64 {
	if x != nil {
		return x.Price3
	}
	return 0
}

func (x *Book) GetInfo() *Book_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

type UpdateBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 操作人
	Op string `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	// 要更新的书籍信息
	Book *Book `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	// 要更新的字段
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookRequest) Reset() {
	*x = UpdateBookRequest{}
	mi := &file_notice_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRequest) ProtoMessage() {}

func (x *UpdateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notice_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return file_notice_proto_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBookRequest) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *UpdateBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *UpdateBookRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type Book_Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             string                 `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book_Info) Reset() {
	*x = Book_Info{}
	mi := &file_notice_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book_Info) ProtoMessage() {}

func (x *Book_Info) ProtoReflect() protoreflect.Message {
	mi := &file_notice_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book_Info.ProtoReflect.Descriptor instead.
func (*Book_Info) Descriptor() ([]byte, []int) {
	return file_notice_proto_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Book_Info) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *Book_Info) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

var File_notice_proto_proto protoreflect.FileDescriptor

const file_notice_proto_proto_rawDesc = "" +
	"\n" +
	"\x12notice_proto.proto\x12\x05proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a google/protobuf/field_mask.proto\"e\n" +
	"\x13NoticeReaderRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\x03 \x01(\tH\x00R\x05phoneB\f\n" +
	"\n" +
	"notice_way\"\xf3\x01\n" +
	"\x04Book\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x1b\n" +
	"\x06price1\x18\x02 \x01(\x03H\x00R\x06price1\x88\x01\x01\x123\n" +
	"\x06price2\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\x06price2\x12\x16\n" +
	"\x06price3\x18\x04 \x01(\x03R\x06price3\x12$\n" +
	"\x04info\x18\x06 \x01(\v2\x10.proto.Book.InfoR\x04info\x1a\"\n" +
	"\x04Info\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\tR\x01bB\t\n" +
	"\a_price1\"\x81\x01\n" +
	"\x11UpdateBookRequest\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x1f\n" +
	"\x04book\x18\x02 \x01(\v2\v.proto.BookR\x04book\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMaskB\x10Z\x0elesson11/protob\x06proto3"

var (
	file_notice_proto_proto_rawDescOnce sync.Once
	file_notice_proto_proto_rawDescData []byte
)

func file_notice_proto_proto_rawDescGZIP() []byte {
	file_notice_proto_proto_rawDescOnce.Do(func() {
		file_notice_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notice_proto_proto_rawDesc), len(file_notice_proto_proto_rawDesc)))
	})
	return file_notice_proto_proto_rawDescData
}

var file_notice_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_notice_proto_proto_goTypes = []any{
	(*NoticeReaderRequest)(nil),   // 0: proto.NoticeReaderRequest
	(*Book)(nil),                  // 1: proto.Book
	(*UpdateBookRequest)(nil),     // 2: proto.UpdateBookRequest
	(*Book_Info)(nil),             // 3: proto.Book.Info
	(*wrapperspb.Int64Value)(nil), // 4: google.protobuf.Int64Value
	(*fieldmaskpb.FieldMask)(nil), // 5: google.protobuf.FieldMask
}
var file_notice_proto_proto_depIdxs = []int32{
	4, // 0: proto.Book.price2:type_name -> google.protobuf.Int64Value
	3, // 1: proto.Book.info:type_name -> proto.Book.Info
	1, // 2: proto.UpdateBookRequest.book:type_name -> proto.Book
	5, // 3: proto.UpdateBookRequest.update_mask:type_name -> google.protobuf.FieldMask
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_notice_proto_proto_init() }
func file_notice_proto_proto_init() {
	if File_notice_proto_proto != nil {
		return
	}
	file_notice_proto_proto_msgTypes[0].OneofWrappers = []any{
		(*NoticeReaderRequest_Email)(nil),
		(*NoticeReaderRequest_Phone)(nil),
	}
	file_notice_proto_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notice_proto_proto_rawDesc), len(file_notice_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notice_proto_proto_goTypes,
		DependencyIndexes: file_notice_proto_proto_depIdxs,
		MessageInfos:      file_notice_proto_proto_msgTypes,
	}.Build()
	File_notice_proto_proto = out.File
	file_notice_proto_proto_goTypes = nil
	file_notice_proto_proto_depIdxs = nil
}
