# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: demo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x02pb\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x02\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x0b\n\x03num\x18\x04 \x01(\x05\x12\r\n\x05score\x18\x05 \x01(\x01\x12(\n\x06\x63orpus\x18\x06 \x01(\x0e\x32\x18.pb.SearchRequest.Corpus\x12/\n\x0b\x44\x61teOfBirth\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"Z\n\x06\x43orpus\x12\r\n\tUNIVERSAL\x10\x00\x12\x07\n\x03WEB\x10\x01\x12\n\n\x06IMAGES\x10\x02\x12\t\n\x05LOCAL\x10\x03\x12\x08\n\x04NEWS\x10\x04\x12\x0c\n\x08PRODUCTS\x10\x05\x12\t\n\x05VIDEO\x10\x06J\x04\x08\x03\x10\x04\"\xf0\x01\n\x0eSearchResponse\x12\x0b\n\x03ret\x18\x01 \x03(\t\x12(\n\x06\x63orpus\x18\x02 \x01(\x0e\x32\x18.pb.SearchRequest.Corpus\x12\x1a\n\x06result\x18\x03 \x01(\x0b\x32\n.pb.Result\x12\x33\n\tmap_field\x18\x04 \x03(\x0b\x32 .pb.SearchResponse.MapFieldEntry\x12%\n\x07\x64\x65tails\x18\x05 \x03(\x0b\x32\x14.google.protobuf.Any\x1a/\n\rMapFieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"N\n\x06Result\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08snippets\x18\x03 \x03(\t\x12\x16\n\x04week\x18\x04 \x01(\x0e\x32\x08.pb.Week\"}\n\rSampleMessage\x12\x0e\n\x04name\x18\x04 \x01(\tH\x00\x12\x33\n\x0bsub_message\x18\t \x01(\x0b\x32\x1c.pb.SampleMessage.SubMessageH\x00\x1a\x19\n\nSubMessage\x12\x0b\n\x03\x61ge\x18\x01 \x01(\x05\x42\x0c\n\ntest_oneof*\x1f\n\x04Week\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06MONDAY\x10\x01\x32@\n\rSearchService\x12/\n\x06Search\x12\x11.pb.SearchRequest\x1a\x12.pb.SearchResponseB\x14Z\x12protobufv3_demo/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022protobufv3_demo/pb'
  _globals['_SEARCHRESPONSE_MAPFIELDENTRY']._loaded_options = None
  _globals['_SEARCHRESPONSE_MAPFIELDENTRY']._serialized_options = b'8\001'
  _globals['_WEEK']._serialized_start=799
  _globals['_WEEK']._serialized_end=830
  _globals['_SEARCHREQUEST']._serialized_start=79
  _globals['_SEARCHREQUEST']._serialized_end=347
  _globals['_SEARCHREQUEST_CORPUS']._serialized_start=251
  _globals['_SEARCHREQUEST_CORPUS']._serialized_end=341
  _globals['_SEARCHRESPONSE']._serialized_start=350
  _globals['_SEARCHRESPONSE']._serialized_end=590
  _globals['_SEARCHRESPONSE_MAPFIELDENTRY']._serialized_start=543
  _globals['_SEARCHRESPONSE_MAPFIELDENTRY']._serialized_end=590
  _globals['_RESULT']._serialized_start=592
  _globals['_RESULT']._serialized_end=670
  _globals['_SAMPLEMESSAGE']._serialized_start=672
  _globals['_SAMPLEMESSAGE']._serialized_end=797
  _globals['_SAMPLEMESSAGE_SUBMESSAGE']._serialized_start=758
  _globals['_SAMPLEMESSAGE_SUBMESSAGE']._serialized_end=783
  _globals['_SEARCHSERVICE']._serialized_start=832
  _globals['_SEARCHSERVICE']._serialized_end=896
# @@protoc_insertion_point(module_scope)
