// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pb/demo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Week int32

const (
	Week_UNKNOWN Week = 0
	Week_MONDAY  Week = 1 // ...
)

// Enum value maps for Week.
var (
	Week_name = map[int32]string{
		0: "UNKNOWN",
		1: "MONDAY",
	}
	Week_value = map[string]int32{
		"UNKNOWN": 0,
		"MONDAY":  1,
	}
)

func (x Week) Enum() *Week {
	p := new(Week)
	*p = x
	return p
}

func (x Week) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Week) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_demo_proto_enumTypes[0].Descriptor()
}

func (Week) Type() protoreflect.EnumType {
	return &file_pb_demo_proto_enumTypes[0]
}

func (x Week) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Week.Descriptor instead.
func (Week) EnumDescriptor() ([]byte, []int) {
	return file_pb_demo_proto_rawDescGZIP(), []int{0}
}

type SearchRequest_Corpus int32

const (
	SearchRequest_UNIVERSAL SearchRequest_Corpus = 0
	SearchRequest_WEB       SearchRequest_Corpus = 1
	SearchRequest_IMAGES    SearchRequest_Corpus = 2
	SearchRequest_LOCAL     SearchRequest_Corpus = 3
	SearchRequest_NEWS      SearchRequest_Corpus = 4
	SearchRequest_PRODUCTS  SearchRequest_Corpus = 5
	SearchRequest_VIDEO     SearchRequest_Corpus = 6 // 枚举值
)

// Enum value maps for SearchRequest_Corpus.
var (
	SearchRequest_Corpus_name = map[int32]string{
		0: "UNIVERSAL",
		1: "WEB",
		2: "IMAGES",
		3: "LOCAL",
		4: "NEWS",
		5: "PRODUCTS",
		6: "VIDEO",
	}
	SearchRequest_Corpus_value = map[string]int32{
		"UNIVERSAL": 0,
		"WEB":       1,
		"IMAGES":    2,
		"LOCAL":     3,
		"NEWS":      4,
		"PRODUCTS":  5,
		"VIDEO":     6,
	}
)

func (x SearchRequest_Corpus) Enum() *SearchRequest_Corpus {
	p := new(SearchRequest_Corpus)
	*p = x
	return p
}

func (x SearchRequest_Corpus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchRequest_Corpus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_demo_proto_enumTypes[1].Descriptor()
}

func (SearchRequest_Corpus) Type() protoreflect.EnumType {
	return &file_pb_demo_proto_enumTypes[1]
}

func (x SearchRequest_Corpus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchRequest_Corpus.Descriptor instead.
func (SearchRequest_Corpus) EnumDescriptor() ([]byte, []int) {
	return file_pb_demo_proto_rawDescGZIP(), []int{0, 0}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // singular 可以设置值也可以不设置值
	PageNumber    int32                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	Num           int32                  `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`                               // float64
	Corpus        SearchRequest_Corpus   `protobuf:"varint,6,opt,name=corpus,proto3,enum=pb.SearchRequest_Corpus" json:"corpus,omitempty"` // 字段编号
	DateOfBirth   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=DateOfBirth,proto3" json:"DateOfBirth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_pb_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_pb_demo_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *SearchRequest) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *SearchRequest) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchRequest) GetCorpus() SearchRequest_Corpus {
	if x != nil {
		return x.Corpus
	}
	return SearchRequest_UNIVERSAL
}

func (x *SearchRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           []string               `protobuf:"bytes,1,rep,name=ret,proto3" json:"ret,omitempty"` // ret = ["a", "b", "c"]
	Corpus        SearchRequest_Corpus   `protobuf:"varint,2,opt,name=corpus,proto3,enum=pb.SearchRequest_Corpus" json:"corpus,omitempty"`
	Result        *Result                `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	MapField      map[string]int32       `protobuf:"bytes,4,rep,name=map_field,json=mapField,proto3" json:"map_field,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // map
	Details       []*anypb.Any           `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty"`                                                                                              // any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_pb_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_pb_demo_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetRet() []string {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *SearchResponse) GetCorpus() SearchRequest_Corpus {
	if x != nil {
		return x.Corpus
	}
	return SearchRequest_UNIVERSAL
}

func (x *SearchResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SearchResponse) GetMapField() map[string]int32 {
	if x != nil {
		return x.MapField
	}
	return nil
}

func (x *SearchResponse) GetDetails() []*anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippets      []string               `protobuf:"bytes,3,rep,name=snippets,proto3" json:"snippets,omitempty"`
	Week          Week                   `protobuf:"varint,4,opt,name=week,proto3,enum=pb.Week" json:"week,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_pb_demo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_pb_demo_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Result) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Result) GetSnippets() []string {
	if x != nil {
		return x.Snippets
	}
	return nil
}

func (x *Result) GetWeek() Week {
	if x != nil {
		return x.Week
	}
	return Week_UNKNOWN
}

type SampleMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TestOneof:
	//
	//	*SampleMessage_Name
	//	*SampleMessage_SubMessage_
	TestOneof     isSampleMessage_TestOneof `protobuf_oneof:"test_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleMessage) Reset() {
	*x = SampleMessage{}
	mi := &file_pb_demo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleMessage) ProtoMessage() {}

func (x *SampleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleMessage.ProtoReflect.Descriptor instead.
func (*SampleMessage) Descriptor() ([]byte, []int) {
	return file_pb_demo_proto_rawDescGZIP(), []int{3}
}

func (x *SampleMessage) GetTestOneof() isSampleMessage_TestOneof {
	if x != nil {
		return x.TestOneof
	}
	return nil
}

func (x *SampleMessage) GetName() string {
	if x != nil {
		if x, ok := x.TestOneof.(*SampleMessage_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *SampleMessage) GetSubMessage() *SampleMessage_SubMessage {
	if x != nil {
		if x, ok := x.TestOneof.(*SampleMessage_SubMessage_); ok {
			return x.SubMessage
		}
	}
	return nil
}

type isSampleMessage_TestOneof interface {
	isSampleMessage_TestOneof()
}

type SampleMessage_Name struct {
	Name string `protobuf:"bytes,4,opt,name=name,proto3,oneof"`
}

type SampleMessage_SubMessage_ struct {
	SubMessage *SampleMessage_SubMessage `protobuf:"bytes,9,opt,name=sub_message,json=subMessage,proto3,oneof"`
}

func (*SampleMessage_Name) isSampleMessage_TestOneof() {}

func (*SampleMessage_SubMessage_) isSampleMessage_TestOneof() {}

type SampleMessage_SubMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Age           int32                  `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleMessage_SubMessage) Reset() {
	*x = SampleMessage_SubMessage{}
	mi := &file_pb_demo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleMessage_SubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleMessage_SubMessage) ProtoMessage() {}

func (x *SampleMessage_SubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_demo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleMessage_SubMessage.ProtoReflect.Descriptor instead.
func (*SampleMessage_SubMessage) Descriptor() ([]byte, []int) {
	return file_pb_demo_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SampleMessage_SubMessage) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_pb_demo_proto protoreflect.FileDescriptor

const file_pb_demo_proto_rawDesc = "" +
	"\n" +
	"\rpb/demo.proto\x12\x02pb\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x02\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12\x10\n" +
	"\x03num\x18\x04 \x01(\x05R\x03num\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x120\n" +
	"\x06corpus\x18\x06 \x01(\x0e2\x18.pb.SearchRequest.CorpusR\x06corpus\x12<\n" +
	"\vDateOfBirth\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vDateOfBirth\"Z\n" +
	"\x06Corpus\x12\r\n" +
	"\tUNIVERSAL\x10\x00\x12\a\n" +
	"\x03WEB\x10\x01\x12\n" +
	"\n" +
	"\x06IMAGES\x10\x02\x12\t\n" +
	"\x05LOCAL\x10\x03\x12\b\n" +
	"\x04NEWS\x10\x04\x12\f\n" +
	"\bPRODUCTS\x10\x05\x12\t\n" +
	"\x05VIDEO\x10\x06J\x04\b\x03\x10\x04\"\xa4\x02\n" +
	"\x0eSearchResponse\x12\x10\n" +
	"\x03ret\x18\x01 \x03(\tR\x03ret\x120\n" +
	"\x06corpus\x18\x02 \x01(\x0e2\x18.pb.SearchRequest.CorpusR\x06corpus\x12\"\n" +
	"\x06result\x18\x03 \x01(\v2\n" +
	".pb.ResultR\x06result\x12=\n" +
	"\tmap_field\x18\x04 \x03(\v2 .pb.SearchResponse.MapFieldEntryR\bmapField\x12.\n" +
	"\adetails\x18\x05 \x03(\v2\x14.google.protobuf.AnyR\adetails\x1a;\n" +
	"\rMapFieldEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"j\n" +
	"\x06Result\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bsnippets\x18\x03 \x03(\tR\bsnippets\x12\x1c\n" +
	"\x04week\x18\x04 \x01(\x0e2\b.pb.WeekR\x04week\"\x94\x01\n" +
	"\rSampleMessage\x12\x14\n" +
	"\x04name\x18\x04 \x01(\tH\x00R\x04name\x12?\n" +
	"\vsub_message\x18\t \x01(\v2\x1c.pb.SampleMessage.SubMessageH\x00R\n" +
	"subMessage\x1a\x1e\n" +
	"\n" +
	"SubMessage\x12\x10\n" +
	"\x03age\x18\x01 \x01(\x05R\x03ageB\f\n" +
	"\n" +
	"test_oneof*\x1f\n" +
	"\x04Week\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06MONDAY\x10\x012@\n" +
	"\rSearchService\x12/\n" +
	"\x06Search\x12\x11.pb.SearchRequest\x1a\x12.pb.SearchResponseB\x14Z\x12protobufv3_demo/pbb\x06proto3"

var (
	file_pb_demo_proto_rawDescOnce sync.Once
	file_pb_demo_proto_rawDescData []byte
)

func file_pb_demo_proto_rawDescGZIP() []byte {
	file_pb_demo_proto_rawDescOnce.Do(func() {
		file_pb_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_demo_proto_rawDesc), len(file_pb_demo_proto_rawDesc)))
	})
	return file_pb_demo_proto_rawDescData
}

var file_pb_demo_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_demo_proto_goTypes = []any{
	(Week)(0),                        // 0: pb.Week
	(SearchRequest_Corpus)(0),        // 1: pb.SearchRequest.Corpus
	(*SearchRequest)(nil),            // 2: pb.SearchRequest
	(*SearchResponse)(nil),           // 3: pb.SearchResponse
	(*Result)(nil),                   // 4: pb.Result
	(*SampleMessage)(nil),            // 5: pb.SampleMessage
	nil,                              // 6: pb.SearchResponse.MapFieldEntry
	(*SampleMessage_SubMessage)(nil), // 7: pb.SampleMessage.SubMessage
	(*timestamppb.Timestamp)(nil),    // 8: google.protobuf.Timestamp
	(*anypb.Any)(nil),                // 9: google.protobuf.Any
}
var file_pb_demo_proto_depIdxs = []int32{
	1, // 0: pb.SearchRequest.corpus:type_name -> pb.SearchRequest.Corpus
	8, // 1: pb.SearchRequest.DateOfBirth:type_name -> google.protobuf.Timestamp
	1, // 2: pb.SearchResponse.corpus:type_name -> pb.SearchRequest.Corpus
	4, // 3: pb.SearchResponse.result:type_name -> pb.Result
	6, // 4: pb.SearchResponse.map_field:type_name -> pb.SearchResponse.MapFieldEntry
	9, // 5: pb.SearchResponse.details:type_name -> google.protobuf.Any
	0, // 6: pb.Result.week:type_name -> pb.Week
	7, // 7: pb.SampleMessage.sub_message:type_name -> pb.SampleMessage.SubMessage
	2, // 8: pb.SearchService.Search:input_type -> pb.SearchRequest
	3, // 9: pb.SearchService.Search:output_type -> pb.SearchResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pb_demo_proto_init() }
func file_pb_demo_proto_init() {
	if File_pb_demo_proto != nil {
		return
	}
	file_pb_demo_proto_msgTypes[3].OneofWrappers = []any{
		(*SampleMessage_Name)(nil),
		(*SampleMessage_SubMessage_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_demo_proto_rawDesc), len(file_pb_demo_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_demo_proto_goTypes,
		DependencyIndexes: file_pb_demo_proto_depIdxs,
		EnumInfos:         file_pb_demo_proto_enumTypes,
		MessageInfos:      file_pb_demo_proto_msgTypes,
	}.Build()
	File_pb_demo_proto = out.File
	file_pb_demo_proto_goTypes = nil
	file_pb_demo_proto_depIdxs = nil
}
