// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: sniff/sniff.proto

package sniff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstanceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ip
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// 端口
	Port int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// 集群
	Cluster string `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// 机房
	Idc string `protobuf:"bytes,4,opt,name=idc,proto3" json:"idc,omitempty"`
	// psm
	Psm           string `protobuf:"bytes,5,opt,name=psm,proto3" json:"psm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceInfo) Reset() {
	*x = InstanceInfo{}
	mi := &file_sniff_sniff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceInfo) ProtoMessage() {}

func (x *InstanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sniff_sniff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceInfo.ProtoReflect.Descriptor instead.
func (*InstanceInfo) Descriptor() ([]byte, []int) {
	return file_sniff_sniff_proto_rawDescGZIP(), []int{0}
}

func (x *InstanceInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *InstanceInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *InstanceInfo) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *InstanceInfo) GetIdc() string {
	if x != nil {
		return x.Idc
	}
	return ""
}

func (x *InstanceInfo) GetPsm() string {
	if x != nil {
		return x.Psm
	}
	return ""
}

type ReqResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Thrift Http1
	Proto string `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	// 请求源
	From *InstanceInfo `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	// 请求目标
	To *InstanceInfo `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	// Thrift request logid
	Logid string `protobuf:"bytes,5,opt,name=logid,proto3" json:"logid,omitempty"`
	// request原始字节流
	Request []byte `protobuf:"bytes,6,opt,name=request,proto3" json:"request,omitempty"`
	// response原始字节流
	Response []byte `protobuf:"bytes,7,opt,name=response,proto3" json:"response,omitempty"`
	// 压测标记
	StressTag   string `protobuf:"bytes,8,opt,name=stress_tag,json=stressTag,proto3" json:"stress_tag,omitempty"`
	DdpTag      string `protobuf:"bytes,9,opt,name=ddp_tag,json=ddpTag,proto3" json:"ddp_tag,omitempty"`
	RingHashKey string `protobuf:"bytes,10,opt,name=ring_hash_key,json=ringHashKey,proto3" json:"ring_hash_key,omitempty"`
	// 方法名
	Method string `protobuf:"bytes,11,opt,name=method,proto3" json:"method,omitempty"`
	// 时间戳
	Timestamp int64 `protobuf:"varint,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 状态码
	StatusCode int32 `protobuf:"varint,13,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// 额外meta信息
	Meta map[string]string `protobuf:"bytes,14,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 源env
	FromEnv string `protobuf:"bytes,15,opt,name=from_env,json=fromEnv,proto3" json:"from_env,omitempty"`
	// 目标env
	ToEnv        string            `protobuf:"bytes,16,opt,name=to_env,json=toEnv,proto3" json:"to_env,omitempty"`
	RequestMeta  map[string]string `protobuf:"bytes,17,rep,name=request_meta,json=requestMeta,proto3" json:"request_meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResponseMeta map[string]string `protobuf:"bytes,18,rep,name=response_meta,json=responseMeta,proto3" json:"response_meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestHash  string            `protobuf:"bytes,19,opt,name=request_hash,json=requestHash,proto3" json:"request_hash,omitempty"`
	PacketbusId  int64             `protobuf:"varint,20,opt,name=packetbus_id,json=packetbusId,proto3" json:"packetbus_id,omitempty"`
	IsEgress     bool              `protobuf:"varint,21,opt,name=is_egress,json=isEgress,proto3" json:"is_egress,omitempty"`
	// sniffer config id
	ConfigId int64 `protobuf:"varint,255,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	// packetbus task id
	TaskId        int64 `protobuf:"varint,256,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqResp) Reset() {
	*x = ReqResp{}
	mi := &file_sniff_sniff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqResp) ProtoMessage() {}

func (x *ReqResp) ProtoReflect() protoreflect.Message {
	mi := &file_sniff_sniff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqResp.ProtoReflect.Descriptor instead.
func (*ReqResp) Descriptor() ([]byte, []int) {
	return file_sniff_sniff_proto_rawDescGZIP(), []int{1}
}

func (x *ReqResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReqResp) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *ReqResp) GetFrom() *InstanceInfo {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ReqResp) GetTo() *InstanceInfo {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ReqResp) GetLogid() string {
	if x != nil {
		return x.Logid
	}
	return ""
}

func (x *ReqResp) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ReqResp) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ReqResp) GetStressTag() string {
	if x != nil {
		return x.StressTag
	}
	return ""
}

func (x *ReqResp) GetDdpTag() string {
	if x != nil {
		return x.DdpTag
	}
	return ""
}

func (x *ReqResp) GetRingHashKey() string {
	if x != nil {
		return x.RingHashKey
	}
	return ""
}

func (x *ReqResp) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ReqResp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReqResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ReqResp) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ReqResp) GetFromEnv() string {
	if x != nil {
		return x.FromEnv
	}
	return ""
}

func (x *ReqResp) GetToEnv() string {
	if x != nil {
		return x.ToEnv
	}
	return ""
}

func (x *ReqResp) GetRequestMeta() map[string]string {
	if x != nil {
		return x.RequestMeta
	}
	return nil
}

func (x *ReqResp) GetResponseMeta() map[string]string {
	if x != nil {
		return x.ResponseMeta
	}
	return nil
}

func (x *ReqResp) GetRequestHash() string {
	if x != nil {
		return x.RequestHash
	}
	return ""
}

func (x *ReqResp) GetPacketbusId() int64 {
	if x != nil {
		return x.PacketbusId
	}
	return 0
}

func (x *ReqResp) GetIsEgress() bool {
	if x != nil {
		return x.IsEgress
	}
	return false
}

func (x *ReqResp) GetConfigId() int64 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *ReqResp) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

var File_sniff_sniff_proto protoreflect.FileDescriptor

const file_sniff_sniff_proto_rawDesc = "" +
	"\n" +
	"\x11sniff/sniff.proto\"t\n" +
	"\fInstanceInfo\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x18\n" +
	"\acluster\x18\x03 \x01(\tR\acluster\x12\x10\n" +
	"\x03idc\x18\x04 \x01(\tR\x03idc\x12\x10\n" +
	"\x03psm\x18\x05 \x01(\tR\x03psm\"\x9e\a\n" +
	"\aReqResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05proto\x18\x02 \x01(\tR\x05proto\x12!\n" +
	"\x04from\x18\x03 \x01(\v2\r.InstanceInfoR\x04from\x12\x1d\n" +
	"\x02to\x18\x04 \x01(\v2\r.InstanceInfoR\x02to\x12\x14\n" +
	"\x05logid\x18\x05 \x01(\tR\x05logid\x12\x18\n" +
	"\arequest\x18\x06 \x01(\fR\arequest\x12\x1a\n" +
	"\bresponse\x18\a \x01(\fR\bresponse\x12\x1d\n" +
	"\n" +
	"stress_tag\x18\b \x01(\tR\tstressTag\x12\x17\n" +
	"\addp_tag\x18\t \x01(\tR\x06ddpTag\x12\"\n" +
	"\rring_hash_key\x18\n" +
	" \x01(\tR\vringHashKey\x12\x16\n" +
	"\x06method\x18\v \x01(\tR\x06method\x12\x1c\n" +
	"\ttimestamp\x18\f \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vstatus_code\x18\r \x01(\x05R\n" +
	"statusCode\x12&\n" +
	"\x04meta\x18\x0e \x03(\v2\x12.ReqResp.MetaEntryR\x04meta\x12\x19\n" +
	"\bfrom_env\x18\x0f \x01(\tR\afromEnv\x12\x15\n" +
	"\x06to_env\x18\x10 \x01(\tR\x05toEnv\x12<\n" +
	"\frequest_meta\x18\x11 \x03(\v2\x19.ReqResp.RequestMetaEntryR\vrequestMeta\x12?\n" +
	"\rresponse_meta\x18\x12 \x03(\v2\x1a.ReqResp.ResponseMetaEntryR\fresponseMeta\x12!\n" +
	"\frequest_hash\x18\x13 \x01(\tR\vrequestHash\x12!\n" +
	"\fpacketbus_id\x18\x14 \x01(\x03R\vpacketbusId\x12\x1b\n" +
	"\tis_egress\x18\x15 \x01(\bR\bisEgress\x12\x1c\n" +
	"\tconfig_id\x18\xff\x01 \x01(\x03R\bconfigId\x12\x18\n" +
	"\atask_id\x18\x80\x02 \x01(\x03R\x06taskId\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10RequestMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11ResponseMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12Z\x10demo/proto/sniffb\x06proto3"

var (
	file_sniff_sniff_proto_rawDescOnce sync.Once
	file_sniff_sniff_proto_rawDescData []byte
)

func file_sniff_sniff_proto_rawDescGZIP() []byte {
	file_sniff_sniff_proto_rawDescOnce.Do(func() {
		file_sniff_sniff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sniff_sniff_proto_rawDesc), len(file_sniff_sniff_proto_rawDesc)))
	})
	return file_sniff_sniff_proto_rawDescData
}

var file_sniff_sniff_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sniff_sniff_proto_goTypes = []any{
	(*InstanceInfo)(nil), // 0: InstanceInfo
	(*ReqResp)(nil),      // 1: ReqResp
	nil,                  // 2: ReqResp.MetaEntry
	nil,                  // 3: ReqResp.RequestMetaEntry
	nil,                  // 4: ReqResp.ResponseMetaEntry
}
var file_sniff_sniff_proto_depIdxs = []int32{
	0, // 0: ReqResp.from:type_name -> InstanceInfo
	0, // 1: ReqResp.to:type_name -> InstanceInfo
	2, // 2: ReqResp.meta:type_name -> ReqResp.MetaEntry
	3, // 3: ReqResp.request_meta:type_name -> ReqResp.RequestMetaEntry
	4, // 4: ReqResp.response_meta:type_name -> ReqResp.ResponseMetaEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sniff_sniff_proto_init() }
func file_sniff_sniff_proto_init() {
	if File_sniff_sniff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sniff_sniff_proto_rawDesc), len(file_sniff_sniff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sniff_sniff_proto_goTypes,
		DependencyIndexes: file_sniff_sniff_proto_depIdxs,
		MessageInfos:      file_sniff_sniff_proto_msgTypes,
	}.Build()
	File_sniff_sniff_proto = out.File
	file_sniff_sniff_proto_goTypes = nil
	file_sniff_sniff_proto_depIdxs = nil
}
