// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: bookstore.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 书架资源。
type Shelf struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 书架的唯一 id。
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 书架上的主题(小说、诗歌等)。
	Theme string `protobuf:"bytes,2,opt,name=theme,proto3" json:"theme,omitempty"`
	// 书架的大小
	Size          int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shelf) Reset() {
	*x = Shelf{}
	mi := &file_bookstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shelf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shelf) ProtoMessage() {}

func (x *Shelf) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shelf.ProtoReflect.Descriptor instead.
func (*Shelf) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{0}
}

func (x *Shelf) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Shelf) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *Shelf) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 图书资源。
type Book struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 图书的唯一 id。
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 图书的作者。
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	// 书名
	Title         string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_bookstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// GetShelf方法的请求消息
type GetShelfRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要获取的书架的id
	ShelfId       int64 `protobuf:"varint,1,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShelfRequest) Reset() {
	*x = GetShelfRequest{}
	mi := &file_bookstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShelfRequest) ProtoMessage() {}

func (x *GetShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShelfRequest.ProtoReflect.Descriptor instead.
func (*GetShelfRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{2}
}

func (x *GetShelfRequest) GetShelfId() int64 {
	if x != nil {
		return x.ShelfId
	}
	return 0
}

// DeleteShelf方法的请求消息
type DeleteShelfRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要删除的书架的id
	ShelfId       int64 `protobuf:"varint,1,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShelfRequest) Reset() {
	*x = DeleteShelfRequest{}
	mi := &file_bookstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShelfRequest) ProtoMessage() {}

func (x *DeleteShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShelfRequest.ProtoReflect.Descriptor instead.
func (*DeleteShelfRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteShelfRequest) GetShelfId() int64 {
	if x != nil {
		return x.ShelfId
	}
	return 0
}

// ListShelves方法的响应消息
type ListShelvesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 所有书架的列表
	Shelves       []*Shelf `protobuf:"bytes,1,rep,name=shelves,proto3" json:"shelves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShelvesResponse) Reset() {
	*x = ListShelvesResponse{}
	mi := &file_bookstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShelvesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShelvesResponse) ProtoMessage() {}

func (x *ListShelvesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShelvesResponse.ProtoReflect.Descriptor instead.
func (*ListShelvesResponse) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{4}
}

func (x *ListShelvesResponse) GetShelves() []*Shelf {
	if x != nil {
		return x.Shelves
	}
	return nil
}

// CreateShelf方法的请求消息
type CreateShelfRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要创建的书架
	Shelf         *Shelf `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShelfRequest) Reset() {
	*x = CreateShelfRequest{}
	mi := &file_bookstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShelfRequest) ProtoMessage() {}

func (x *CreateShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShelfRequest.ProtoReflect.Descriptor instead.
func (*CreateShelfRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{5}
}

func (x *CreateShelfRequest) GetShelf() *Shelf {
	if x != nil {
		return x.Shelf
	}
	return nil
}

// Request message for ListBooks method.
type ListBooksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the shelf which books to list.
	ShelfId       int64  `protobuf:"varint,1,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksRequest) Reset() {
	*x = ListBooksRequest{}
	mi := &file_bookstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksRequest) ProtoMessage() {}

func (x *ListBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksRequest.ProtoReflect.Descriptor instead.
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{6}
}

func (x *ListBooksRequest) GetShelfId() int64 {
	if x != nil {
		return x.ShelfId
	}
	return 0
}

func (x *ListBooksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListBooks 方法的请求消息。
type ListBooksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 书架上的图书。
	Books         []*Book `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	NextPageToken string  `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksResponse) Reset() {
	*x = ListBooksResponse{}
	mi := &file_bookstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksResponse) ProtoMessage() {}

func (x *ListBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksResponse.ProtoReflect.Descriptor instead.
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{7}
}

func (x *ListBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

func (x *ListBooksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// CreateBook 方法的请求消息。
type CreateBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要在其上创建图书的书架的 ID。
	ShelfId int64 `protobuf:"varint,1,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	// 在书架上创建的图书数据。
	Book          *Book `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_bookstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{8}
}

func (x *CreateBookRequest) GetShelfId() int64 {
	if x != nil {
		return x.ShelfId
	}
	return 0
}

func (x *CreateBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

// GetBook 方法的请求消息。
type GetBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要从中检索图书的书架的 ID。
	ShelfId int64 `protobuf:"varint,1,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	// 要检索的图书的 ID。
	BookId        int64 `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_bookstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{9}
}

func (x *GetBookRequest) GetShelfId() int64 {
	if x != nil {
		return x.ShelfId
	}
	return 0
}

func (x *GetBookRequest) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

// DeleteBook 方法的请求消息。
type DeleteBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要从中删除图书的书架的 ID。
	ShelfId int64 `protobuf:"varint,1,opt,name=shelf_id,json=shelfId,proto3" json:"shelf_id,omitempty"`
	// 要删除的图书的 ID。
	BookId        int64 `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookRequest) Reset() {
	*x = DeleteBookRequest{}
	mi := &file_bookstore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRequest) ProtoMessage() {}

func (x *DeleteBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookstore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return file_bookstore_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBookRequest) GetShelfId() int64 {
	if x != nil {
		return x.ShelfId
	}
	return 0
}

func (x *DeleteBookRequest) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

var File_bookstore_proto protoreflect.FileDescriptor

const file_bookstore_proto_rawDesc = "" +
	"\n" +
	"\x0fbookstore.proto\x12\tbookstore\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"A\n" +
	"\x05Shelf\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05theme\x18\x02 \x01(\tR\x05theme\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"D\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\",\n" +
	"\x0fGetShelfRequest\x12\x19\n" +
	"\bshelf_id\x18\x01 \x01(\x03R\ashelfId\"/\n" +
	"\x12DeleteShelfRequest\x12\x19\n" +
	"\bshelf_id\x18\x01 \x01(\x03R\ashelfId\"A\n" +
	"\x13ListShelvesResponse\x12*\n" +
	"\ashelves\x18\x01 \x03(\v2\x10.bookstore.ShelfR\ashelves\"<\n" +
	"\x12CreateShelfRequest\x12&\n" +
	"\x05shelf\x18\x01 \x01(\v2\x10.bookstore.ShelfR\x05shelf\"L\n" +
	"\x10ListBooksRequest\x12\x19\n" +
	"\bshelf_id\x18\x01 \x01(\x03R\ashelfId\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"b\n" +
	"\x11ListBooksResponse\x12%\n" +
	"\x05books\x18\x01 \x03(\v2\x0f.bookstore.BookR\x05books\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"S\n" +
	"\x11CreateBookRequest\x12\x19\n" +
	"\bshelf_id\x18\x01 \x01(\x03R\ashelfId\x12#\n" +
	"\x04book\x18\x02 \x01(\v2\x0f.bookstore.BookR\x04book\"D\n" +
	"\x0eGetBookRequest\x12\x19\n" +
	"\bshelf_id\x18\x01 \x01(\x03R\ashelfId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\x03R\x06bookId\"G\n" +
	"\x11DeleteBookRequest\x12\x19\n" +
	"\bshelf_id\x18\x01 \x01(\x03R\ashelfId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\x03R\x06bookId2\xb5\x06\n" +
	"\tBookstore\x12X\n" +
	"\bGetShelf\x12\x1a.bookstore.GetShelfRequest\x1a\x10.bookstore.Shelf\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/shelves/{shelf_id}\x12d\n" +
	"\vDeleteShelf\x12\x1d.bookstore.DeleteShelfRequest\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/v1/shelves/{shelf_id}\x12Z\n" +
	"\vListShelves\x12\x16.google.protobuf.Empty\x1a\x1e.bookstore.ListShelvesResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/shelves\x12Z\n" +
	"\vCreateShelf\x12\x1d.bookstore.CreateShelfRequest\x1a\x10.bookstore.Shelf\"\x1a\x82\xd3\xe4\x93\x02\x14:\x05shelf\"\v/v1/shelves\x12l\n" +
	"\tListBooks\x12\x1b.bookstore.ListBooksRequest\x1a\x1c.bookstore.ListBooksResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/shelves/{shelf_id}/books\x12g\n" +
	"\n" +
	"CreateBook\x12\x1c.bookstore.CreateBookRequest\x1a\x0f.bookstore.Book\"*\x82\xd3\xe4\x93\x02$:\x04book\"\x1c/v1/shelves/{shelf_id}/books\x12e\n" +
	"\aGetBook\x12\x19.bookstore.GetBookRequest\x1a\x0f.bookstore.Book\".\x82\xd3\xe4\x93\x02(\x12&/v1/shelves/{shelf_id}/books/{book_id}\x12r\n" +
	"\n" +
	"DeleteBook\x12\x1c.bookstore.DeleteBookRequest\x1a\x16.google.protobuf.Empty\".\x82\xd3\xe4\x93\x02(*&/v1/shelves/{shelf_id}/books/{book_id}B\x17Z\x15lesson23/bookstore/pbb\x06proto3"

var (
	file_bookstore_proto_rawDescOnce sync.Once
	file_bookstore_proto_rawDescData []byte
)

func file_bookstore_proto_rawDescGZIP() []byte {
	file_bookstore_proto_rawDescOnce.Do(func() {
		file_bookstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bookstore_proto_rawDesc), len(file_bookstore_proto_rawDesc)))
	})
	return file_bookstore_proto_rawDescData
}

var file_bookstore_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_bookstore_proto_goTypes = []any{
	(*Shelf)(nil),               // 0: bookstore.Shelf
	(*Book)(nil),                // 1: bookstore.Book
	(*GetShelfRequest)(nil),     // 2: bookstore.GetShelfRequest
	(*DeleteShelfRequest)(nil),  // 3: bookstore.DeleteShelfRequest
	(*ListShelvesResponse)(nil), // 4: bookstore.ListShelvesResponse
	(*CreateShelfRequest)(nil),  // 5: bookstore.CreateShelfRequest
	(*ListBooksRequest)(nil),    // 6: bookstore.ListBooksRequest
	(*ListBooksResponse)(nil),   // 7: bookstore.ListBooksResponse
	(*CreateBookRequest)(nil),   // 8: bookstore.CreateBookRequest
	(*GetBookRequest)(nil),      // 9: bookstore.GetBookRequest
	(*DeleteBookRequest)(nil),   // 10: bookstore.DeleteBookRequest
	(*emptypb.Empty)(nil),       // 11: google.protobuf.Empty
}
var file_bookstore_proto_depIdxs = []int32{
	0,  // 0: bookstore.ListShelvesResponse.shelves:type_name -> bookstore.Shelf
	0,  // 1: bookstore.CreateShelfRequest.shelf:type_name -> bookstore.Shelf
	1,  // 2: bookstore.ListBooksResponse.books:type_name -> bookstore.Book
	1,  // 3: bookstore.CreateBookRequest.book:type_name -> bookstore.Book
	2,  // 4: bookstore.Bookstore.GetShelf:input_type -> bookstore.GetShelfRequest
	3,  // 5: bookstore.Bookstore.DeleteShelf:input_type -> bookstore.DeleteShelfRequest
	11, // 6: bookstore.Bookstore.ListShelves:input_type -> google.protobuf.Empty
	5,  // 7: bookstore.Bookstore.CreateShelf:input_type -> bookstore.CreateShelfRequest
	6,  // 8: bookstore.Bookstore.ListBooks:input_type -> bookstore.ListBooksRequest
	8,  // 9: bookstore.Bookstore.CreateBook:input_type -> bookstore.CreateBookRequest
	9,  // 10: bookstore.Bookstore.GetBook:input_type -> bookstore.GetBookRequest
	10, // 11: bookstore.Bookstore.DeleteBook:input_type -> bookstore.DeleteBookRequest
	0,  // 12: bookstore.Bookstore.GetShelf:output_type -> bookstore.Shelf
	11, // 13: bookstore.Bookstore.DeleteShelf:output_type -> google.protobuf.Empty
	4,  // 14: bookstore.Bookstore.ListShelves:output_type -> bookstore.ListShelvesResponse
	0,  // 15: bookstore.Bookstore.CreateShelf:output_type -> bookstore.Shelf
	7,  // 16: bookstore.Bookstore.ListBooks:output_type -> bookstore.ListBooksResponse
	1,  // 17: bookstore.Bookstore.CreateBook:output_type -> bookstore.Book
	1,  // 18: bookstore.Bookstore.GetBook:output_type -> bookstore.Book
	11, // 19: bookstore.Bookstore.DeleteBook:output_type -> google.protobuf.Empty
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_bookstore_proto_init() }
func file_bookstore_proto_init() {
	if File_bookstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bookstore_proto_rawDesc), len(file_bookstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bookstore_proto_goTypes,
		DependencyIndexes: file_bookstore_proto_depIdxs,
		MessageInfos:      file_bookstore_proto_msgTypes,
	}.Build()
	File_bookstore_proto = out.File
	file_bookstore_proto_goTypes = nil
	file_bookstore_proto_depIdxs = nil
}
