# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: add.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'add.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tadd.proto\x12\x02pb\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"8\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\r\x12\x0b\n\x03msg\x18\x03 \x01(\t24\n\nAddService\x12&\n\x03\x41\x64\x64\x12\x0e.pb.AddRequest\x1a\x0f.pb.AddResponseB\x11Z\x0fhello_server/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'add_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017hello_server/pb'
  _globals['_ADDREQUEST']._serialized_start=17
  _globals['_ADDREQUEST']._serialized_end=51
  _globals['_ADDRESPONSE']._serialized_start=53
  _globals['_ADDRESPONSE']._serialized_end=109
  _globals['_ADDSERVICE']._serialized_start=111
  _globals['_ADDSERVICE']._serialized_end=163
# @@protoc_insertion_point(module_scope)
